version: "3.8"

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: arshad-alpine
        container_name: arshad-ag
        restart: unless-stopped
        working_dir: /var/www/html
        tty: true
        ports:
            - "8002:8080"
        volumes:
            - ./:/var/www/html
        networks:
            - arshad
    mariadb:
      image: mariadb:11.2
      container_name: arshad-db
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_PASSWORD=123456
        - MYSQL_DATABASE=arshad_db
        - MYSQL_USER=arshad_db_user
      volumes:
        - db_dataa:/var/lib/mysql
        - .docker/dev/config/mysqlconf:/etc/mysql/conf.d
      ports:
        - "3308:3306"
      networks:
        - arshad

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mariadb
      environment:
        - PMA_HOST=mariadb
        - UPLOAD_LIMIT=64M
      restart: always
      ports:
        - "8091:80"
      networks:
        - arshad

    redis:
        image: redis:alpine
        container_name: arshad-redis
        hostname: redis
        networks:
            - arshad
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

networks:
  arshad:

volumes:
  db_dataa:

